export const FILTER_PROJECTS = 'FILTER_PROJECTS'
export const CHOOSE_ITEM = 'CHOOSE_ITEM'
export const START_GAME = 'START_GAME'
export const FINISH_GAME = 'FINISH_GAME'
export const END_GAME = 'END_GAME'
export const SET_WINDOW_SIZE = 'SET_WINDOW_SIZE'
